version: '1.0'
services: 
  db: 
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inlazedb
    ports:
      - 5432:5432